config/routes.rb
Rails.application.routes.draw do
  resources :coupons
  resources :orders
  resources :addresses
  devise_for :users
  resources :reviews
  resources :categories
  resources :products
  resources :cart_line_items
  resources :wishlist_items

  get 'say/goodbye'
  get 'say/hello'
  root 'say#hello'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  def initialize(user)
    if user.nil?
        can :read, [Category, Product]
    elsif user.role? "admin"
        can :manage, [Category, Product, Review]
    elsif user.role? "moderator"
        can :read, [Category, Product, Review]
        can :create, Review
        # can :update, [Category, Product]
        can :destroy, Review
    elsif user.role? "customer"
        can :read, [Category, Product]
        can :create, Product
        can [:read, :create] ,Review
        can [:update, :destroy], Review do |review|
            review.user_id == user.id
        end        
    end 
  end
end

app/models/address.rb
class Address < ApplicationRecord
validates_presence_of :name, :details, :street, :landmark, :user_id, :pincode, :state, :city
belongs_to :user
has_many :orders
end

app/models/cart_line_item.rb
class CartLineItem < ApplicationRecord
	belongs_to :product
	belongs_to :user
	validates_presence_of :product_id, :user_id, :quantity

	def save_or_update
		line_item = CartLineItem.find_by(user_id: self.user_id, product_id: self.product_id)
		if line_item.nil?
			self.save
		else
		line_item.update_attributes(quantity: line_item.quantity + self.quantity)
		end
	end
end

app/models/category.rb
class Category < ApplicationRecord
validates_presence_of :name, :description
validates_uniqueness_of :name
has_many :products
end

app/models/coupon.rb
class Coupon < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :user
	belongs_to :address
	has_many :order_line_items

	before_validation :set_number_date_total
	after_create :move_to_order_line_items
	after_create :empty_cart_line_items
	after_create :update_stock
	validates_presence_of :order_number, :order_date, :user_id, :total, :address_id

	def set_number_date_total
		self.order_number = "DCT#{Random.rand(10000)}"
		self.order_date = Date.today
		self.total = calculate_total
	end

	def calculate_total
		total = 0
		self.user.cart_line_items.each do |line_item|
			total += (line_item.quantity * line_item.product.price)
		end
		return total
	end

	def move_to_order_line_items
		self.user.cart_line_items.each do |line_item|
		OrderLineItem.create(product_id: line_item.product_id, quantity: line_item.quantity, price: line_item.product.price, order_id: self.id)
	end
	end

	def update_stock
		self.order_line_items.each do |line_item|
			line_item.product.update_attributes(stock: line_item.product.stock - line_item.quantity)
		end
	end

	def empty_cart_line_items
		CartLineItem.delete(self.user.cart_line_items.pluck(:id))
	end
end

app/models/order_line_item.rb
class OrderLineItem < ApplicationRecord
	belongs_to :product
	belongs_to :order

	validates_presence_of :order_id, :product_id, :price, :quantity
end

app/models/permission.rb
class Permission < ApplicationRecord
	belongs_to :user
	belongs_to :role
end

app/models/product.rb
class Product < ApplicationRecord
validates_presence_of :name, :description, :category_id, :price, :stock
validates_length_of :description, minimum: 5
belongs_to :category
has_many :reviews
has_many :order_line_items
has_many :cart_line_items
has_many :wishlist_items
end

app/models/profile.rb
class Profile < ApplicationRecord
end

app/models/review.rb
class Review < ApplicationRecord
validates_presence_of :body, :product_id, :rating, :user_id
validates_length_of :body, within: 10...1000
belongs_to :product
belongs_to :user
end

app/models/role.rb
class Role < ApplicationRecord
	has_many :permissions
	has_many :users, through: :permissions
validates_presence_of :name
validates_uniqueness_of :name

end

app/models/user.rb
class User < ApplicationRecord
	has_many :reviews
	has_many :permissions
  has_many :orders
	has_many :roles, through: :permissions
  has_many :cart_line_items
  has_many :wishlist_items
  has_many :addresses
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         validates_presence_of :username, :mobile
         validates_numericality_of :mobile
         validates_length_of :mobile, is:10

         after_create :assign_customer_role

         def assign_customer_role
         	Permission.create(user_id: self.id, role_id: Role.last.id)
         end
         def role?(role)
         	self.roles.pluck(:name).include?(role)
         end
end

app/models/wishlist_item.rb
class WishlistItem < ApplicationRecord
	belongs_to :product
	belongs_to :user
	validates_presence_of :product_id, :user_id
	validates_uniqueness_of :user_id, scope: :product_id

	def move_to_cart
		CartLineItem.new(user_id: self.user_id, product_id: self.product_id, quantity: 1).save_or_update
		self.destroy
	end

end

app/controllers/coupons_controller.rb
class CouponsController < ApplicationController
  before_action :set_coupon, only: [:show, :edit, :update, :destroy]

  # GET /coupons
  # GET /coupons.json
  def index
    @coupons = Coupon.all
  end

  # GET /coupons/1
  # GET /coupons/1.json
  def show
  end

  # GET /coupons/new
  def new
    @coupon = Coupon.new
  end

  # GET /coupons/1/edit
  def edit
  end

  # POST /coupons
  # POST /coupons.json
  def create
    @coupon = Coupon.new(coupon_params)

    respond_to do |format|
      if @coupon.save
        format.html { redirect_to @coupon, notice: 'Coupon was successfully created.' }
        format.json { render :show, status: :created, location: @coupon }
      else
        format.html { render :new }
        format.json { render json: @coupon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coupons/1
  # PATCH/PUT /coupons/1.json
  def update
    respond_to do |format|
      if @coupon.update(coupon_params)
        format.html { redirect_to @coupon, notice: 'Coupon was successfully updated.' }
        format.json { render :show, status: :ok, location: @coupon }
      else
        format.html { render :edit }
        format.json { render json: @coupon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coupons/1
  # DELETE /coupons/1.json
  def destroy
    @coupon.destroy
    respond_to do |format|
      format.html { redirect_to coupons_url, notice: 'Coupon was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coupon
      @coupon = Coupon.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def coupon_params
      params.require(:coupon).permit(:code, :discount, :expiry_date)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/coupons_helper.rb
module CouponsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/say_helper.rb
module SayHelper
end

app/views/coupons/_form.html.erb
<%= form_with(model: coupon, local: true) do |form| %>
  <% if coupon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(coupon.errors.count, "error") %> prohibited this coupon from being saved:</h2>

      <ul>
      <% coupon.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :code %>
    <%= form.text_field :code, id: :coupon_code %>
  </div>

  <div class="field">
    <%= form.label :discount %>
    <%= form.number_field :discount, id: :coupon_discount %>
  </div>

  <div class="field">
    <%= form.label :expiry_date %>
    <%= form.datetime_select :expiry_date, id: :coupon_expiry_date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/coupons/edit.html.erb
<h1>Editing Coupon</h1>

<%= render 'form', coupon: @coupon %>

<%= link_to 'Show', @coupon %> |
<%= link_to 'Back', coupons_path %>

app/views/coupons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Coupons</h1>

<table>
  <thead>
    <tr>
      <th>Code</th>
      <th>Discount</th>
      <th>Expiry date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @coupons.each do |coupon| %>
      <tr>
        <td><%= coupon.code %></td>
        <td><%= coupon.discount %></td>
        <td><%= coupon.expiry_date %></td>
        <td><%= link_to 'Show', coupon %></td>
        <td><%= link_to 'Edit', edit_coupon_path(coupon) %></td>
        <td><%= link_to 'Destroy', coupon, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Coupon', new_coupon_path %>

app/views/coupons/new.html.erb
<h1>New Coupon</h1>

<%= render 'form', coupon: @coupon %>

<%= link_to 'Back', coupons_path %>

app/views/coupons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @coupon.code %>
</p>

<p>
  <strong>Discount:</strong>
  <%= @coupon.discount %>
</p>

<p>
  <strong>Expiry date:</strong>
  <%= @coupon.expiry_date %>
</p>

<%= link_to 'Edit', edit_coupon_path(@coupon) %> |
<%= link_to 'Back', coupons_path %>