config/routes.rb
Rails.application.routes.draw do
  resources :coupons
  resources :orders
  resources :addresses
  devise_for :users
  resources :reviews
  resources :categories
  resources :products
  resources :cart_line_items
  resources :wishlist_items

  get 'say/goodbye'
  get 'say/hello'
  root 'say#hello'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  def initialize(user)
    if user.nil?
        can :read, [Category, Product]
    elsif user.role? "admin"
        can :manage, [Category, Product, Review]
    elsif user.role? "moderator"
        can :read, [Category, Product, Review]
        can :create, Review
        # can :update, [Category, Product]
        can :destroy, Review
    elsif user.role? "customer"
        can :read, [Category, Product]
        can :create, Product
        can [:read, :create] ,Review
        can [:update, :destroy], Review do |review|
            review.user_id == user.id
        end        
    end 
  end
end

app/models/address.rb
class Address < ApplicationRecord
validates_presence_of :name, :details, :street, :landmark, :user_id, :pincode, :state, :city
belongs_to :user
has_many :orders
end

app/models/cart_line_item.rb
class CartLineItem < ApplicationRecord
	belongs_to :product
	belongs_to :user
	validates_presence_of :product_id, :user_id, :quantity

	def save_or_update
		line_item = CartLineItem.find_by(user_id: self.user_id, product_id: self.product_id)
		if line_item.nil?
			self.save
		else
		line_item.update_attributes(quantity: line_item.quantity + self.quantity)
		end
	end
end

app/models/category.rb
class Category < ApplicationRecord
validates_presence_of :name, :description
validates_uniqueness_of :name
has_many :products
end

app/models/coupon.rb
class Coupon < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :user
	belongs_to :address
	has_many :order_line_items

	before_validation :set_number_date_total
	after_create :move_to_order_line_items
	after_create :empty_cart_line_items
	after_create :update_stock
	validates_presence_of :order_number, :order_date, :user_id, :total, :address_id

	def set_number_date_total
		self.order_number = "DCT#{Random.rand(10000)}"
		self.order_date = Date.today
		self.total = calculate_total
	end

	def calculate_total
		total = 0
		self.user.cart_line_items.each do |line_item|
			total += (line_item.quantity * line_item.product.price)
		end
		return total
	end

	def move_to_order_line_items
		self.user.cart_line_items.each do |line_item|
		OrderLineItem.create(product_id: line_item.product_id, quantity: line_item.quantity, price: line_item.product.price, order_id: self.id)
	end
	end

	def update_stock
		self.order_line_items.each do |line_item|
			line_item.product.update_attributes(stock: line_item.product.stock - line_item.quantity)
		end
	end

	def empty_cart_line_items
		CartLineItem.delete(self.user.cart_line_items.pluck(:id))
	end
end

app/models/order_line_item.rb
class OrderLineItem < ApplicationRecord
	belongs_to :product
	belongs_to :order

	validates_presence_of :order_id, :product_id, :price, :quantity
end

app/models/permission.rb
class Permission < ApplicationRecord
	belongs_to :user
	belongs_to :role
end

app/models/product.rb
class Product < ApplicationRecord
validates_presence_of :name, :description, :category_id, :price, :stock
validates_length_of :description, minimum: 5
belongs_to :category
has_many :reviews
has_many :order_line_items
has_many :cart_line_items
has_many :wishlist_items
end

app/models/profile.rb
class Profile < ApplicationRecord
end

app/models/review.rb
class Review < ApplicationRecord
validates_presence_of :body, :product_id, :rating, :user_id
validates_length_of :body, within: 10...1000
belongs_to :product
belongs_to :user
end

app/models/role.rb
class Role < ApplicationRecord
	has_many :permissions
	has_many :users, through: :permissions
validates_presence_of :name
validates_uniqueness_of :name

end

app/models/user.rb
class User < ApplicationRecord
	has_many :reviews
	has_many :permissions
  has_many :orders
	has_many :roles, through: :permissions
  has_many :cart_line_items
  has_many :wishlist_items
  has_many :addresses
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         validates_presence_of :username, :mobile
         validates_numericality_of :mobile
         validates_length_of :mobile, is:10

         after_create :assign_customer_role

         def assign_customer_role
         	Permission.create(user_id: self.id, role_id: Role.last.id)
         end
         def role?(role)
         	self.roles.pluck(:name).include?(role)
         end
end

app/models/wishlist_item.rb
class WishlistItem < ApplicationRecord
	belongs_to :product
	belongs_to :user
	validates_presence_of :product_id, :user_id
	validates_uniqueness_of :user_id, scope: :product_id

	def move_to_cart
		CartLineItem.new(user_id: self.user_id, product_id: self.product_id, quantity: 1).save_or_update
		self.destroy
	end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

	before_action :authenticate_user!, except: [:index, :show]
	load_and_authorize_resource
def index
	@categories = Category.all
end
def new
	@category = Category.new
end
def create
	@category = Category.new(category_params)
	if @category.save
		redirect_to categories_path(@category.id), notice: "The category was successfully updated"
	else
		render action: 'new'
	end
end
def show
	@category = Category.find(params[:id])
end
def edit
	@category = Category.find(params[:id])
end
def update
	@category = Category.find(params[:id])
	if @category.update_attributes(category_params)
		redirect_to categories_path(@category.id), notice: "The category was successfully updated"
	else
		render action: "edit"
	end
end
def destroy
	@category = Category.find(params[:id])
	@category.destroy
		redirect_to categories_path, notice: "The category was successfully updated"
end

private

def category_params
	params[:category].permit(:name, :description)
end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/coupons_helper.rb
module CouponsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/say_helper.rb
module SayHelper
end

app/views/categories/_form.html.erb
<%= form_for @category do |f| %>

<% if @category.errors.any? %>
<h3>These errors prohibited the form from being saved</h3>
<ul>
	<% @category.errors.full_messages.each do |msg| %>
	<li><%= msg %></li>
	<% end %>
</ul>
<% end %>

<label for="category_name"> Name : </label> <br/>
<%= f.text_field :name, placeholder: "Enter name" %> <span id="nameMsg"></span><br/>

<label for="category_description"> Description : </label> <br/>
<%= f.text_area :description, placeholder: "Enter description" %> <span id="bodyMsg"></span><br/>


<%= f.submit %>

<% end %>

<script>
	var nameHandle = document.getElementById('category_name');
	var nameMsgHandle = document.getElementById('nameMsg');

	nameHandle.addEventListener('focus', function(){
		nameMsgHandle.innerHTML = "Enter the category name";
	}, false)


	nameHandle.addEventListener('blur', function(){
		if(nameHandle.value == ""){
			nameMsgHandle.innerHTML = "can't be blank";
		}else {
			nameMsgHandle.innerHTML = "";
		}
	}, false);

	var bodyHandle = document.getElementById('category_description');
	var bodyMsgHandle = document.getElementById('bodyMsg');

	bodyHandle.addEventListener('focus', function(){
		bodyMsgHandle.innerHTML = "Enter the category description";
	}, false)


	bodyHandle.addEventListener('blur', function(){
		if(bodyHandle.value == ""){
			bodyMsgHandle.innerHTML = "can't be blank";
		}else {
			bodyMsgHandle.innerHTML = "";
		}
	}, false);
</script>

app/views/categories/edit.html.erb
<h2>Edit Category</h2>
<%= render 'form' %>

app/views/categories/index.html.erb
<h2>Listing Categories (<%= @categories.length %>)</h2>
<br/>
<% if @categories.empty? %>
    <p>No Blogs</p>
    <% else %>
<ol>
        <div class="row">
             <% @categories.each do |category| %>
            <div class="col-lg-4 col-md-6 mb-4">
              <div class="card h-100">
                <div class="card-body">
                  <h4 class="card-title">
                    <%= link_to category.name%></h4>
                  <p class="card-text"><%= category.description %></p>
                </div>
                <div class="card-footer">
                  <small class="text-muted"> <%= category.name%> has (<%= category.products.count %>) products</small>
                </div>
              </div>
            </div>
            <% end %>
          </div>
        <!-- <%#= link_to category.name, category_path(category.id) %> - (<%#= category.products.count %>) -->
</ol>
<% end %>
<%# if user_signed_in? %>
<%#= link_to "Add Categories", new_category_path%>
<%# end %>








 

app/views/categories/new.html.erb
<h2>Add Category</h2>
<%= render 'form' %>

app/views/categories/show.html.erb
<h2><%= @category.name %></h2>
 
<div class="row", id="productList">
            <div class="col-lg-4 col-md-6 mb-4">
              <div class="card h-100">
                <div class="card-body">
                  <h4 class="card-title">
                    <%= link_to @category.name%></h4>
                  <p class="card-text"><%= @category.description %></p>
                </div>
                <div class="card-footer">
                  <small class="text-muted"> Category has (<%= @category.products.count %>) products</small>
                </div>
              </div>
            </div>
          </div>
          <br>
<%= link_to "Categories list",categories_path %></br>
</br>
<p><% if user_signed_in? %><%= link_to "edit", edit_category_path(@category.id) %> | <%= link_to "delete", category_path(@category.id), method: :delete, data: {confirm: "Are you sure? "}%> <% end %></p>