config/routes.rb
Rails.application.routes.draw do
  resources :coupons
  resources :orders
  resources :addresses
  devise_for :users
  resources :reviews
  resources :categories
  resources :products
  resources :cart_line_items
  resources :wishlist_items

  get 'say/goodbye'
  get 'say/hello'
  root 'say#hello'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
validates_presence_of :name, :description, :category_id, :price, :stock
validates_length_of :description, minimum: 5
belongs_to :category
has_many :reviews
has_many :order_line_items
has_many :cart_line_items
has_many :wishlist_items
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
before_action :authenticate_user!, except: [:index, :show]
load_and_authorize_resource
#url - hhtp://localhost:3000/products
#uri - /products
#path - product_path
#http method - GET
#roles & resposibility - to list all products
def index
	@products = Product.paginate(:page => params[:page], :per_page => 9)
    @product = Product.new
    @category = Category.new
end

#url - http://localhost:3000/products/new
#uri - /products/new
#path - new_product_path
#http method - GET
#roles & resposibility - is to setup a form for adding a new product
def new
	@product = Product.new
end

def create
	@product = Product.new(params[:product].permit(:name, :feature_image_url, :description, :price, :stock, :category_id))
	if @product.save
		redirect_to products_path
	else
		render action: 'new'
	end
end	

#url - http://localhost:3000/products/:id
#uri - /products/:id
#path - product_path(id)
#http method - GET
#roles & resposibility - to find the product from the database and display it on the show page , this page will be used to show all the data about the product and also associated information like all reviews, all q&a's, add product to cart  

def show
	@products = Product.all
	@product = Product.find(params[:id])
	@review = Review.new
end

#url - http://localhost:3000/products/:id/edit
#uri - /products/:id/edit
#path - edit_product_path(id)
#http method - GET
#roles & resposibility - to find the record the user is trying to edit , and display it on a form

def edit
	@product = Product.find(params[:id])
end

#url - http://localhost:3000/products/:id
#uri - /products/:id
#path - product_path(id)
#http method - PATCH
#roles & resposibility - find the record, the user just updated in the browser, and update its information by taking the data coming in from the form , validate the object, if the validations pass update the record to the db and redirect the user to a show page , alse display the errors on the form

def update 
@product = Product.find(params[:id])
if @product.update_attributes(params[:product].permit(:name, :feature_image_url, :description, :price, :stock, :category_id))
	redirect_to products_path(@product.id)
else
	render action: 'edit'
end
end

#url - http://localhost:3000/products/:id
#uri - /products/:id
#path - product_path(id)
#http method - PATCH
#roles & resposibility - find the record, the user just updated in the browser, and update its information by taking the data coming in from the form , validate the object, if the validations pass update the record to the db and redirect the user to a show page , alse display the errors on the form

def destroy 
@product = Product.find(params[:id])
@product.destroy
     redirect_to products_path, notice: "The product was successfully destroyed"
end 

private
 def product_params
     params[:product].permit(:name, :description, :feature_image_url, :price, :stock, :category_id)
end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for @product do |f| %>
<% if @product.errors.any? %>
<h3>These errors prohibited the form from being saved:</h3>
<ul>
	<% @product.errors.full_messages.each do |msg| %>
	<li><%= msg %></li>
	<% end %>

<% end %>
</ul>
<label> <for="product_category_id"> Category : </label><br/>
<%= f.collection_select :category_id, Category.all, :id, :name, prompt: "Select Category" %> <br/>

<label> <for= "product_name"> Name : </label><br/>
<%= f.text_field :name, placeholder: "enter name" %> <span id="nameMsg"></span><br/>

<label> <for= "product_description"> Description : </label><br/>
<%= f.text_field :description %> <br/>

<label> <for= "product_feature_image_url"> Image : </label><br/>
<%= f.text_field :feature_image_url %> <br/>

<label> <for= "product_price"> Price : </label><br/>
<%= f.number_field :price, min: 1 %> <br/>

<label> <for= "product_stock"> Stock : </label><br/>
<%= f.number_field :stock, min: 0 %> <br/>

<%= f.submit %>
<% end %>

<script>
	var nameHandle = document.getElementById("product_name")
	var nameMsgHandle = document.getElementById("nameMsg")

	nameHandle.addEventListener("focus", fuction(){
		nameMsgHandle.innerHTML = "enter the product name"
	}, false);

	nameHandle.addEventListener("blur" fuction(){
		if(nameHandle.value == ""){
		nameMsgHandle.innerHTML = "cant be blank";
	}
	else{
		nameMsgHandle.innerHTML="";
	}, false)
</script>

app/views/products/edit.html.erb
<h2>Edit Product</h2>
<%= render 'form' %>

app/views/products/index.html.erb
<div class="row">

	<div class="col-lg-4">

		<h1 class="my-4"> <%= link_to Category, categories_path%></h1>
		<%Category.all.each do |category|%>
		<div class="list-group">
			<a href="/categories/<%=category.id%>" class="list-group-item"><%=category.name%></a>     
		</div>
		<%end%>
		<br/>

		<div class="row">
			<div class="col-md-4">
				<button type="button" class="btn btn-link" data-toggle="modal" data-target="#exampleModal">
				<h2>Add Category</h2>
				</button>
			</div>
		</div>

		<br/>

		<div class="row">
			<div class="col-md-4">
				<h2>Add Product</h2>
				<%= render 'form', product: @product%>
			</div>
		</div>

	</div>
	<!-- /.col-lg-3 -->

	<div class="col-lg-8">
		<h3>Listing Products (<%= @products.length %>)</h3>
		<div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
			<ol class="carousel-indicators">
				<li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
				<li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
				<li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
			</ol>
			<div class="carousel-inner" role="listbox">
				<div class="carousel-item active">
					<!-- <img class="d-block img-fluid" src="2bfc21.jpg/900x350" alt="First slide"> -->
					<%= image_tag("MiTV3-b.png", size: "900x350") %>
				</div>
				<div class="carousel-item">
					<!-- <img class="d-block img-fluid" src="91f645.jpg/900x350" alt="Second slide"> -->
					<%= image_tag("ix.png", size: "900x350") %>
				</div>
				<div class="carousel-item">
					<!-- <img class="d-block img-fluid" src="91f645.jpg/900x350" alt="Second slide"> -->
					<%= image_tag("ipad1", size: "900x350") %>
				</div>
			</div>
			<a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
				<span class="carousel-control-prev-icon" aria-hidden="true"></span>
				<span class="sr-only">Previous</span>
			</a>
			<a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
				<span class="carousel-control-next-icon" aria-hidden="true"></span>
				<span class="sr-only">Next</span>
			</a>
		</div>

		<div class="row">

			<div class="row", id="productList">
				<% @products.each do |product| %>
				<div class="col-lg-4 col-md-6 mb-4">
					<div class="card h-100">
						<%= image_tag("#{product.feature_image_url}", size: "150x100") %>
						<div class="card-body">
							<h4 class="card-title">
								<%= link_to product.name, product_path(product.id) %></h4>
								<h5> Price - <%= product.price%> rs</h5>
								<p class="card-text"><%= product.description.truncate(20) %></p>
							</div>
							<div class="card-footer">
								<small class="text-muted"> Belongs to <%=product.category.name %></small>
							</div>
						</div>
					</div>
					<%end%>
				</div>



			</div>
			<!-- /.row -->

		</div>
		<!-- /.col-lg-9 -->

	</div>
	<!-- /.row -->

	<%= will_paginate(@products, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer) %>




	<%# if @products.empty? %>
	<!-- <p>No Products Found.</p> -->
	<%#else %>
	<!-- <ol> -->
		<%# @products.each do |product| %>
		<!-- <li><%#= product.name %> - INR <%#= product.price %> - <%#= product.description %> -  -->
			<%# if !product.category.nil? %>
			<%#= product.category.name %>
			<%# end %> 
			<%#= link_to "show", product_path(product.id) %>
			<!-- </li> -->
			<%# end %>
		<!-- </ol> -->

		<%# end%>
		<%# if (user_signed_in?) && (can? :create, Product.new) %>
		<%#= link_to "Add Product", new_product_path %>
		<%# end %>
		<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
			<div class="modal-dialog" role="document">
				<div class="modal-content">
					<div class="modal-header">
						<h5 class="modal-title" id="exampleModalLabel">Add Category</h5>
						<button type="button" class="close" data-dismiss="modal" aria-label="Close">
							<span aria-hidden="true">&times;</span>
						</button>
					</div>
					<div class="modal-body">
						<%= render '/categories/form', category: @category %>
					</div>

				</div>
			</div>
		</div>

		

app/views/products/new.html.erb
<h2>Add Product</h2>
<%= render 'form' %>

app/views/products/show.html.erb
<h1><%= @product.name%></h1>
<p>
<% if (user_signed_in?) && (can? :update, @product) %>
<%= link_to "edit", edit_product_path(@product.id) %> | 
<%= link_to "delete", product_path(@product.id),method: :delete, data: {confirm: "Are you sure?"} %><% end %>
</p>
<p> <%= @product.description %></p>
<p> INR <%= @product.price %></p>
<% if !@product.category.nil? %>
<%= link_to @product.category.name, category_path(@product.category_id) %>
<% end %> <br/>
<%#= link_to "List products", products_path %>


<h2>Add to Cart</h2>
<% if user_signed_in? %>
<%= form_for CartLineItem.new do |f|%>
<label>Quantity :</label>
<%= f.select :quantity, (1..10).to_a %> <br/>
<%= f.hidden_field :product_id, value: @product.id %>
<%= f.submit "Add to Cart" %> 
<% end %>
<%= form_for WishlistItem.new do |f|%>
<%= f.hidden_field :product_id, value: @product.id %>
<%= f.submit "Add to Wishlist" %> 
<% end %>
<% else %>
<p>You need to sign in first.</p>
<% end %>

<% if @product.reviews.empty? %>
<p>No reviews found. Be the first one to review.</p>
<% else %>
<h3> Listing Reviews </h3>
<ol id="reviewList">
<% @product.reviews.each do |review| %>
<li id="review_<%= review.id %>">
<%= review.body %> - (<%= review.rating %>) - <%= review.user_id %><% if (user_signed_in?) && (can? :update ,review) %><%= link_to "edit", edit_review_path(review.id) %> | <%= link_to "destroy", review_path(review.id),method: :delete, data: {confirm: "Are you sure you want to delete this review"}, remote: true %><% end %>
</li>
<% end %>
</ol>
<% end %>
<% if !user_signed_in? %>
<p> Login to add a review</p>
<% else%>
<p id="reviewNotice"></p>

<h3>Add your review</h3>
<div id="reviewError"></div>
<%= form_for(@review, remote: true) do |f| %>

<label for="review_body"> Body </label> <br/>
<%= f.text_area :body %> <br/>

<%= f.hidden_field :product_id, value: @product.id %>

<br/>
<label> Rating </label> <br/>
<%= f.radio_button :rating, 1 %> 1
<%= f.radio_button :rating, 2 %> 2
<%= f.radio_button :rating, 3 %> 3
<%= f.radio_button :rating, 4 %> 4
<%= f.radio_button :rating, 5 %> 5 <br/>
<%= f.submit "create" %>
<% end %>
<% end %>