config/routes.rb
Rails.application.routes.draw do
  resources :coupons
  resources :orders
  resources :addresses
  devise_for :users
  resources :reviews
  resources :categories
  resources :products
  resources :cart_line_items
  resources :wishlist_items

  get 'say/goodbye'
  get 'say/hello'
  root 'say#hello'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  def initialize(user)
    if user.nil?
        can :read, [Category, Product]
    elsif user.role? "admin"
        can :manage, [Category, Product, Review]
    elsif user.role? "moderator"
        can :read, [Category, Product, Review]
        can :create, Review
        # can :update, [Category, Product]
        can :destroy, Review
    elsif user.role? "customer"
        can :read, [Category, Product]
        can :create, Product
        can [:read, :create] ,Review
        can [:update, :destroy], Review do |review|
            review.user_id == user.id
        end        
    end 
  end
end

app/models/address.rb
class Address < ApplicationRecord
validates_presence_of :name, :details, :street, :landmark, :user_id, :pincode, :state, :city
belongs_to :user
has_many :orders
end

app/models/cart_line_item.rb
class CartLineItem < ApplicationRecord
	belongs_to :product
	belongs_to :user
	validates_presence_of :product_id, :user_id, :quantity

	def save_or_update
		line_item = CartLineItem.find_by(user_id: self.user_id, product_id: self.product_id)
		if line_item.nil?
			self.save
		else
		line_item.update_attributes(quantity: line_item.quantity + self.quantity)
		end
	end
end

app/models/category.rb
class Category < ApplicationRecord
validates_presence_of :name, :description
validates_uniqueness_of :name
has_many :products
end

app/models/coupon.rb
class Coupon < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :user
	belongs_to :address
	has_many :order_line_items

	before_validation :set_number_date_total
	after_create :move_to_order_line_items
	after_create :empty_cart_line_items
	after_create :update_stock
	validates_presence_of :order_number, :order_date, :user_id, :total, :address_id

	def set_number_date_total
		self.order_number = "DCT#{Random.rand(10000)}"
		self.order_date = Date.today
		self.total = calculate_total
	end

	def calculate_total
		total = 0
		self.user.cart_line_items.each do |line_item|
			total += (line_item.quantity * line_item.product.price)
		end
		return total
	end

	def move_to_order_line_items
		self.user.cart_line_items.each do |line_item|
		OrderLineItem.create(product_id: line_item.product_id, quantity: line_item.quantity, price: line_item.product.price, order_id: self.id)
	end
	end

	def update_stock
		self.order_line_items.each do |line_item|
			line_item.product.update_attributes(stock: line_item.product.stock - line_item.quantity)
		end
	end

	def empty_cart_line_items
		CartLineItem.delete(self.user.cart_line_items.pluck(:id))
	end
end

app/models/order_line_item.rb
class OrderLineItem < ApplicationRecord
	belongs_to :product
	belongs_to :order

	validates_presence_of :order_id, :product_id, :price, :quantity
end

app/models/permission.rb
class Permission < ApplicationRecord
	belongs_to :user
	belongs_to :role
end

app/models/product.rb
class Product < ApplicationRecord
validates_presence_of :name, :description, :category_id, :price, :stock
validates_length_of :description, minimum: 5
belongs_to :category
has_many :reviews
has_many :order_line_items
has_many :cart_line_items
has_many :wishlist_items
end

app/models/profile.rb
class Profile < ApplicationRecord
end

app/models/review.rb
class Review < ApplicationRecord
validates_presence_of :body, :product_id, :rating, :user_id
validates_length_of :body, within: 10...1000
belongs_to :product
belongs_to :user
end

app/models/role.rb
class Role < ApplicationRecord
	has_many :permissions
	has_many :users, through: :permissions
validates_presence_of :name
validates_uniqueness_of :name

end

app/models/user.rb
class User < ApplicationRecord
	has_many :reviews
	has_many :permissions
  has_many :orders
	has_many :roles, through: :permissions
  has_many :cart_line_items
  has_many :wishlist_items
  has_many :addresses
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         validates_presence_of :username, :mobile
         validates_numericality_of :mobile
         validates_length_of :mobile, is:10

         after_create :assign_customer_role

         def assign_customer_role
         	Permission.create(user_id: self.id, role_id: Role.last.id)
         end
         def role?(role)
         	self.roles.pluck(:name).include?(role)
         end
end

app/models/wishlist_item.rb
class WishlistItem < ApplicationRecord
	belongs_to :product
	belongs_to :user
	validates_presence_of :product_id, :user_id
	validates_uniqueness_of :user_id, scope: :product_id

	def move_to_cart
		CartLineItem.new(user_id: self.user_id, product_id: self.product_id, quantity: 1).save_or_update
		self.destroy
	end

end

app/helpers/coupons_helper.rb
module CouponsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/say_helper.rb
module SayHelper
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <div class="container">
    <%= image_tag("eco", size: "65x45") %>
    <a class="navbar-brand" href="#">Ecommerce</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <%= link_to "Home", say_hello_path, class: "nav-link"%>
          <span class="sr-only">(current)</span>
        </li>
        <li class="nav-item">
          <%= link_to "Products", products_path, class: "nav-link"%>
        </li>
            <!-- <li class="nav-item">
              <a class="nav-link" href="#">Services</a>
            </li> -->
            <li class="nav-item dropdown <%= controller.controller_name == 'categories' ? 'active' : ''%>">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Categories
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
               <% Category.all.each do |category| %>
               <!-- <a class="dropdown-item" href="#">Action</a> -->
               <%= link_to category.name, category, class: 'dropdown-item' %>
               <% end %>
             </div>
           </li>
           <li class="nav-item">
            <% if user_signed_in? %> 
            <!-- welcome <%#= current_user.email %>  -->
            <%= link_to "Your Cart(#{current_user.cart_line_items.pluck(:quantity).inject(:+)})", cart_line_items_path, class: "nav-link" %>
            <li><%= link_to "Your Wishlist Cart(#{current_user.wishlist_items.count})", wishlist_items_path, class: "nav-link" %></li>
            <%= link_to "Addresses", addresses_path, class: "nav-link" %>
            <li><%= link_to "Account Setting", edit_user_registration_path, class: "nav-link" %></li>
            <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "nav-link" %> 
            <% else %>
            <%= link_to "Register", new_user_registration_path, class: "nav-link" %><li><%= link_to "Login", new_user_session_path, class: "nav-link" %></li>  
            <% end %>
          </li>

        </ul>
      </div>
    </div>
  </nav>
  <div class="mb-4"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pro</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js" type="text/javascript"></script>
  <script src="/javascripts/jquery.growl.js" type="text/javascript"></script>
  <script src="/javascripts/jquery.js"></script>
  <script src="/javascripts/bootstrap.js"></script>
  <script src="/javascripts/jquery-ui.js"></script>

  <link rel="stylesheet" href="/stylesheets/bootstrap.css" />
  <link rel="stylesheet" href="/stylesheets/shop-homepage.css" />
  <link rel="stylesheet" href="/stylesheets/shop-item.css" />
  <link rel="stylesheet" href="/stylesheets/jquery-ui.css" />
  <link href="/stylesheets/jquery.growl.css" rel="stylesheet" type="text/css" />
</head>

<body>
  <%= render "/layouts/nav" %>
  <div class="container">
   <%# if user_signed_in? %> 
   <!-- welcome <%#= current_user.email %>  -->
   <!-- <%#= link_to "Your Cart(#{current_user.cart_line_items.pluck(:quantity).inject(:+)})", cart_line_items_path %> | -->
   <!-- <%#= link_to "Your Wishlist Cart(#{current_user.wishlist_items.count})", wishlist_items_path %> | -->
   <!-- <%#= link_to "Addresses", addresses_path %> | -->
   <!-- <%#= link_to "Account Setting", edit_user_registration_path %>  | <%#= link_to "Logout", destroy_user_session_path, method: :delete %> |  -->
   <%# else %>
   <!-- <%#= link_to "Register", new_user_registration_path %> | <%#= link_to "Login", new_user_session_path %> |  -->
   <%# end %>

   <!-- <%#= link_to "Categories", categories_path %> | -->
   <!-- <%#= link_to "Products", products_path%> | -->
   <!-- <%#= link_to "Home", say_hello_path%> | -->
   <!-- <%#= link_to "About Us", say_goodbye_path%> | -->
   <!-- <%#= link_to "Google", "http://www.google.com", :target => "_blank"%> | -->
   <!-- <%#= link_to "Gmail", "http://www.gmail.com", :target => "_blank"%> | -->
   <%#= link_to "DCT", "http://www.dctacademy.com", :target => "_blank"%>
   <br/>

   <%= notice %>
   <%= alert %>

   <%= yield %>
 </div>
 <%# if user_signed_in? %>
 <!-- <p> You current IP (<%#= current_user.current_sign_in_ip %>) </p> -->
 <%# end %>
</body>
</html>